### ISSUE TITLE
Getting ERR_MODULE_NOT_FOUND after recent PR, basic AssemblyScript example fails

### ISSUE THREAD

**Issue by JulianDM1995** [AssemblyScript/assemblyscript#2787] opened 2023-11-09 17:28 UTC
### Bug description

Hello there,

I've encountered an issue after a recent pull request merge where even the basic AssemblyScript example (from the official [Getting Started](https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project) guide) is no longer working. This was functional just before the latest changes were introduced.

Here's the error message I'm receiving:

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/julianmedina/Desktop/CraftyEngine/wasm/StringArtStudio/node_modules/assemblyscript/dist/asc.js' imported from /Users/julianmedina/Desktop/CraftyEngine/wasm/StringArtStudio/node_modules/assemblyscript/bin/asc.js
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at finalizeResolution (node:internal/modules/esm/resolve:231:11)
    at moduleResolve (node:internal/modules/esm/resolve:850:10)
    at defaultResolve (node:internal/modules/esm/resolve:1058:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:416:18)
    at ESMLoader.import (node:internal/modules/esm/loader:517:22)
    at importModuleDynamically (node:internal/modules/esm/translators:108:35)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:85:14)
    at file:///Users/julianmedina/Desktop/CraftyEngine/wasm/StringArtStudio/node_modules/assemblyscript/bin/asc.js:29:21
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  code: 'ERR_MODULE_NOT_FOUND'
}`

### Steps to reproduce

Not even the Assemblyscript example works now

https://www.assemblyscript.org/getting-started.html#setting-up-a-new-project

### AssemblyScript version

^0.27.15

**Comment by CountBleck** [comment] 2023-11-09 17:53
Duplicate of #2784.

**Comment by CountBleck** [comment] 2023-11-09 18:56
@JulianDM1995 It should be fixed now.

**Closed** 2023-11-09 18:57 UTC
Labels: bug, duplicate

**Comment by JulianDM1995** [comment] 2023-11-09 18:58
Works fine now. Thanks!
