### ISSUE TITLE
Support anyref as a field type of a class

### ISSUE THREAD

**Issue by flyhawk1010** [AssemblyScript/assemblyscript#2314] opened 2022-06-09 07:36 UTC
**Code:**
```
class EntityProxy {
    private refEntity: anyref;
      constructor(refEntity: anyref) {
        this.refEntity = refEntity;
    }
}
export const proxy = new EntityProxy(null);
```

**Output:**

```
Whoops, the AssemblyScript compiler has crashed during compile :-(

Here is the stack trace hinting at the problem, perhaps it's useful?
/Users/bruce/Projects/libs/node_modules/assemblyscript/std/portable/index.js:200
     throw new AssertionError(message);
     
AssertionError: assertion failed
     at q.assert (/Users/bruce/Projects/libs/node_modules/assemblyscript/std/portable/index.js:200:11)
     at Zn.finishResolveClass (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/resolver.ts:3205:13)
     at Zn.resolveClass (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/resolver.ts:2999:10)
     at Zn.resolveClassInclTypeArguments (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/resolver.ts:3428:17)
     at oi.compileNewExpression (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:8787:37)
     at oi.compileExpression (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:3449:21)
     at oi.compileGlobal (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:1082:25)
     at oi.compileTopLevelStatement (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:2062:20)
     at oi.compileFile (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:1013:12)
     at oi.compile (/Users/bruce/Projects/libs/node_modules/assemblyscript/src/compiler.ts:497:14)
```

Is it possible to support **anyref** as a field type of a class?

**Comment by trusktr** [comment] 2022-06-11 18:00
Are you talking about `externref`? There's no `anyref` type in AS.

**Comment by trusktr** [comment] 2022-06-11 18:03
Duplicate of https://github.com/AssemblyScript/assemblyscript/issues/1859

**Comment by MaxGraey** [comment] 2022-06-11 18:04
> Are you talking about externref ([see types](https://www.assemblyscript.org/types.html#types))? There's no anyref type in AS.

Basically with latest changes `anyref` was superseded `externref`. Currently `externref` is just an alias of `anyref`

**Closed by trusktr** 2022-06-11 18:03 UTC
