### ISSUE TITLE
Low-Cost Vectors, Colors, Structs

### ISSUE THREAD

**Issue by mattdesl** [AssemblyScript/assemblyscript#2721] opened 2023-07-21 09:53 UTC
### Feature suggestion

I have some code that deals with geometry and graphics programming, where Vectors and Colors are often needed. However, I'd like to avoid allocating new memory, or using classes, if possible. I've noticed the performance, bundle size, and complexity (in terms of dealing with Wasm Memory) are much smaller and more manageable when just using variables, or even global variables, so I wonder how to achieve some of these things with AssemblyScript.

Example use case:

```js
struct Vec2 {
  x:f32;
  y:f32;
}

function normalize (vec:Vec2):void {
  let len:f32 = vec.x * vec.x + vec.y * vec.y;
  if (len > 0) {
    let f:f32 = Mathf.sqrt(len);
    vec.x /= f;
    vec.y /= f;
  }
}

export function init ():void {
  let a:Vec2 = Vec2(0.5, 0.25);
  normalize(a);
  /* do something with a.x, a.y */
}
```

I don't really care for functions, memory management, or other features of classes, and I don't want my bundle size to bloat with each new class definition. Really I am just using this as a sort of tuple. Is this possible?

**Comment by Heath123** [comment] 2023-07-21 10:30
I think this is a duplicate of #2254

**Comment by CountBleck** [comment] 2023-07-21 10:36
Your proposed syntax wouldn't really be compatible with TS in any way. I suppose TS has a syntax for tuple types (e.g. `const foo: [i32, f64, string] = [123, 4.56, "78 9"];`), and a subset of that could be added to AS. However, those tuples are still pass-by-reference in TS, and that can't be done in AS without allocating memory.

Maybe some sort of custom pass-by-value tuple type could be added, although it wouldn't be available for portable code. ~~That would incidentally be a pretty nice way to implement support for multi-value returns in AS.~~ (It appears @Heath123 beat me to this point while I was typing this out.)

Since you're also looking for performance improvements, maybe `v128` is of interest to you. It can fit four `f32`s/two `f64`s and allows you to potentially make code faster by using SIMD ops.

**Comment by mattdesl** [comment] 2023-07-21 11:14
Thanks. I am OK with any syntax really; or a decorator. Since this is a dupe we can close and continue discussion in the other topic.

In this case, SIMD is interesting but for my use case it will involve a lot of extracting/loading/storing which makes me wonder if it would be as performant, even something like `normalize()` I have not found a simple way with AssemblyScript's SIMD to achieve f32 dot (or horizontal add after f32x4.mul), and then an extract to compare against zero.

**Comment by CountBleck** [comment] 2023-07-21 11:56
SIMD would likely be more helpful if/when you loop over a bunch of vectors and do some calculations.

Anyways, I might as well close this then...

**Closed by CountBleck** 2023-07-21 11:56 UTC
Labels: duplicate, enhancement
