### ISSUE TITLE
ERROR AS219: Optional properties are not supported

### ISSUE THREAD

**Issue by mariusa** [AssemblyScript/assemblyscript#2591] opened 2022-12-11 08:29 UTC
Couldn't find this referenced anywhere (except an unrelated issue).

Are class Optional properties planned to be supported?
```
class Employee {
  firstName: string;
  lastName: string;
  middleName?: string;
}
```

**Comment by CountBleck** [comment] 2022-12-11 16:43
I'm not sure. The issue is that `undefined` doesn't exist in AssemblyScript. You should be able to use `middleName: string | null = null;` instead.

**Comment by mariusa** [comment] 2022-12-11 20:22
Thanks!

Shall I leave the issue open for Optional properties support, or that doesn't make sense?

**Comment by CountBleck** [comment] 2022-12-12 23:25
I'll just close this

**Closed by CountBleck** 2022-12-12 23:25 UTC

**Comment by mariusa** [comment] 2022-12-13 12:43
FYI I tried that for numbers
`age: f32 | null = null`

but get ERROR AS204: Type 'f32' cannot be nullable.

**Comment by CountBleck** [comment] 2022-12-13 22:56
Primitives aren't nullable. References (including strings and `externref`s) are nullable. You can omit ` | null = null` to get a default value to be assigned (zero). If that doesn't suit you, you could use -1 or maybe even NaN.

**Comment by mariusa** [comment] 2022-12-14 20:32
Sorry to bug you about this, found a case which just doesn't work without optional properties.
I need to integrate with a 3rd party which wants either one or another property (of a JSON object), but not both. It won't accept `null`, returns an error that only one of those keys should be set (as documented).

I tried:
1. setting to null the unexpected property
2. having 2 separate classes and a function which returns one or the other, but that is not possible
3. deleting the unexpected property later in code (`delete obj.prop`), gives error can't delete required property

**Comment by dcodeIO** [comment] 2022-12-14 21:37
Either 1. or 2. should work. 1 is limited by whether the type can be nullable, whereas 2 needs a base class with two extenders, then further down doing an `instanceof` / cast. The other options don't seem feasible.

**Comment by mariusa** [comment] 2022-12-15 06:07
Appreciate your insight, thanks.
