### ISSUE TITLE
Avoid masking/sign extension between function calls

### ISSUE THREAD

**Issue by CryZe** [AssemblyScript/assemblyscript#38] opened 2018-03-11 18:28 UTC
Booleans, u8, i8, u16 and i16 are optimized poorly it seems. There is a lot of masking going on at the moment that is not necessary.

Consider the following two functions:
```ts
export function add16(x: i16, y: i16): i16 {
  return x + y;
}

export function add32(x: i32, y: i32): i32 {
  return x + y;
}
```
They get compiled down to:
```wat
  (func $main/add16 (export "add16") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.add
    i32.const 16
    i32.shl
    i32.const 16
    i32.shr_s
    return)
  (func $main/add32 (export "add32") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p0
    get_local $p1
    i32.add
    return)
```
As you can see, the add16 function has a lot of masking operations, while the add32 is just a pure addition. Compare this to the following Rust code:
```rust
#[no_mangle]
pub extern fn add16(x: i16, y: i16) -> i16 {
  x + y
}

#[no_mangle]
pub extern fn add32(x: i32, y: i32) -> i32 {
  x + y
}
```
Which gets compiled down to the following code:
```wat
  (func $add16 (export "add16") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p1
    get_local $p0
    i32.add)
  (func $add32 (export "add32") (type $t0) (param $p0 i32) (param $p1 i32) (result i32)
    get_local $p1
    get_local $p0
    i32.add)
```
As you can see, they are the same, as adding two i16 values is the same as adding two i32 values, because the upper 16-bits of the 32-bit wide "register" is getting masked away anyway when storing the 16-bit wide value in memory with a i32.store16_u instruction. So there's only very few instructions where actual masking is necessary (like dividing).

**Comment by dcodeIO** [comment] 2018-03-11 19:59
But, if you call this from JS now, with two valid integers in 16-bit range, the result seen on the JS-side wouldn't be in 16-bit range if it overflows, wouldn't it?

**Comment by CryZe** [comment] 2018-03-11 20:06
Mmh, that's a good point. Weird how this is completely ignored by LLVM at the moment. I think exports / imports probably require masking their arguments / return values. Everything inside of WebAssembly however doesn't need any masking.

**Comment by dcodeIO** [comment] 2018-03-14 01:04
Another thing that comes to my mind here is that this sequence

```wat
    i32.const 16
    i32.shl
    i32.const 16
    i32.shr_s
```

is going to replaced with a [sign extension operation](https://github.com/WebAssembly/sign-extension-ops) in the future. That's just the way it needs to be done at this point in time. The body would then look like

```wat
    get_local $p0
    get_local $p1
    i32.add
    i32.extend16_s
    return
```

if I understood this correctly.

**Comment by CryZe** [comment] 2018-03-15 16:03
I'm not sure if it's possible, but I think you'd need to be able to determine the ABI of a function. So if you know a function is being exported to JS, you want to do the sign / zero extension (vice versa for the imports) and for everything internal you want to skip it. Interestingly our discussion here caused this bug to be found in [Rust](https://github.com/rust-lang-nursery/rust-wasm/issues/88). So for Rust the external functions are all marked with the C ABI and will do the sign / zero extension, while all internal functions (so the Rust ABI) won't. I'm not sure if you could do something similar. An automatic analysis may not be possible, as function pointers may be ambiguous otherwise. For function pointers you could however always assume it's the "assemblyscript" abi and have an assemblyscript abi wrapper for all the c abi functions (i.e. the exported ones).

**Comment by dcodeIO** [comment] 2018-03-15 16:20
I agree, so this could be summarized by *avoiding masking/sign extension between function calls*. Shouldn't be too hard to implement for direct calls. Indirect calls should be doable as well, as long as restrictions on function signatures prohibit interchanging return types, which it currently looks like.

**Comment by MaxGraey** [comment] 2018-03-21 17:16
I think this also related to current issue. Implicitly casting from ```bool``` to ```i32``` produce extra code. For example:

```ts
export function foo(a: i32): i32 {
  return a > 0;
}
``` 
Out (optimized):
```
get_local $p0
i32.const 0
i32.gt_s
i32.const 1
i32.add
i32.const 1
i32.and
```

But with explicit:
```ts
export function foo(a: i32): i32 {
  return <i32>(a > 0);
}
```
Output (optimized):
```
get_local $p0
i32.const 0
i32.gt_s
```

**Comment by dcodeIO** [comment] 2018-03-21 17:23
Hmm, this

```ts
export function foo(a: i32): i32 {
  return a > 0;
}
```

compiles to

```s
 (func $foo (; 0 ;) (type $ii) (param $0 i32) (result i32)
  (return
   (i32.gt_s
    (get_local $0)
    (i32.const 0)
   )
  )
 )
```

for me without optimizations.

**Comment by MaxGraey** [comment] 2018-03-21 17:31
It seems yes, but with -O3 flag. I checked in Web Assembly Studio. It seems this happen with -O2s

**Comment by dcodeIO** [comment] 2018-03-21 17:33
I didn't perform any optimizations to see what the compiler itself is generating. Optimizations are a Binaryen-only thing. Maybe I missed something to reproduce this properly?

**Comment by MaxGraey** [comment] 2018-03-21 17:36
Sorry, I publish slightly different version. Actually I mean this:

```ts
export function foo(a: i32): i32 {
  return (a > 0) + 1;
}
```

**Comment by dcodeIO** [comment] 2018-03-21 18:08
I believe it's not looking up the contextual type there, so it doesn't know that whatever value comes from `bool + i32` doesn't have to be wrapped. Most likely not the only thing that needs to be improved when wrapping (or better: not wrapping).

**Comment by CryZe** [comment] 2018-04-27 20:58
That sounds good so far.

**Comment by dcodeIO** [comment] 2018-04-28 01:13
Just hit this one: https://github.com/WebAssembly/binaryen/issues/1521

**Comment by dcodeIO** [comment] 2018-05-05 22:06
This should be handled in https://github.com/AssemblyScript/assemblyscript/pull/87 now. Might still be missing a few obvious or not-so-obvious cases in [canOverflow](https://github.com/AssemblyScript/assemblyscript/blob/50f6c1c4605067bc13dfb467d4f4d8ee876137a5/src/program.ts#L3868) - if anyone would like to take a look :)

Closing for now, but feel free to reopen if there are significant issues.

**Closed by dcodeIO** 2018-05-05 22:06 UTC
Labels: enhancement :rocket:
