### ISSUE TITLE
Large alloc causes unreachable

### ISSUE THREAD

**Issue by Addeventure** [AssemblyScript/assemblyscript#701] opened 2019-07-01 19:19 UTC
Creating an Uint8Array with a value higher than 6553600 bytes causes unreachable

assembly/index.ts:
```
export function createUint8Array(size: i32): Uint8Array {
    return new Uint8Array(size);
}
```

src/index.js:

```
...
let instance = loader.instantiate(compiled, imports);
let arrayRef = instance.createUint8Array(6553601);
```

Output:
```
abort called at index.ts: '0 NaN:15
wasm://wasm/5721d722:10

RuntimeError: unreachable
    at ~lib/rt/tlsf/allocateBlock (wasm-function[9]:52)
    at ~lib/rt/tlsf/__alloc (wasm-function[10]:23)
    at ~lib/arraybuffer/ArrayBufferView#constructor (wasm-function[28]:40)
    at ~lib/typedarray/Uint8Array#constructor (wasm-function[29]:21)
    at assembly/index/createUint8Array (wasm-function[30]:5)
```

**Comment by dcodeIO** [comment] 2019-07-02 19:21
Did the module do other allocations previously that could lead to the memory being fragmented in a way that allocating another block would fail? Or did it run long enough without calling `__gc_collect()` that memory might be fully utilized?

**Comment by MaxGraey** [comment] 2019-07-02 19:37
@dcodeIO I reproduced this issue:
https://webassembly.studio/?f=i1702nkc2kb

**Comment by MaxGraey** [comment] 2019-07-02 19:42
Some interesting things:
```ts
alloc(6553600 * 2) // ok 
alloc(6553600 * 2 + 1) // fail
```

**Comment by dcodeIO** [comment] 2019-07-04 01:48
So I've tried the following in a local test:

```ts
export function createUint8Array(size: i32): Uint8Array {
  return new Uint8Array(size);
}

createUint8Array(6553600);
createUint8Array(6553600 + 1);

__alloc(6553600 * 2, 0);
__alloc(6553600 * 2 + 1, 0);
```

which works with and without last dist files. Am I missing something?

**Comment by dcodeIO** [comment] 2019-07-04 02:18
So it looks like what's happening here is that memory is grown by the flat amount necessary, while not properly rounded to guarantee that the next invocation of `searchBlock` will succeed, hence hitting the assertion for certain sizes. Should have a fix soon :)

**Comment by MaxGraey** [comment] 2019-07-28 05:39
Should be fixed

**Closed by MaxGraey** 2019-07-28 05:39 UTC
Labels: bug
