### ISSUE TITLE
default export syntax not supported yet? (or regression?)

### ISSUE THREAD

**Issue by trusktr** [AssemblyScript/assemblyscript#627] opened 2019-06-02 20:26 UTC
I'm unable to use default exports, f.e. `import Size from './Size'`. It gives me a syntax error during build.

See this issue for more details: https://github.com/jtenner/as-pect/issues/71

**Comment by willemneal** [comment] 2019-06-03 13:06
As someone who has only been in the typescript/javascript community for a little over a year and a half, I'm still unsure what the benefits to a default import are.  Personally, I find them annoying because it seems they are the exception and make things less flexible.  This is not to say I'm totally against them, just want to know why you find them useful other than not writing `{ Size }`.

**Comment by dcodeIO** [comment] 2019-06-04 01:50
Duplicate of https://github.com/AssemblyScript/assemblyscript/issues/98

**Closed by dcodeIO** 2019-06-04 01:50 UTC
