### ISSUE TITLE
issue in AssemblyScript for subgraph

### ISSUE THREAD

**Issue by Ortiz2525** [AssemblyScript/assemblyscript#2742] opened 2023-09-14 22:54 UTC
### Bug description

I'm using your assemblyscript for subgraph mapping typescript.
this is my typescript code 
```
export function handleCollect(event: CollectEvent): void { }
```
 when type "graph build", it doesn't occur errors in above case.
but
```
export function handleCollect(event: CollectEvent): void { if(event.transaction.to == null) {}}
```
in this case AssemblyScript occurs error.

### Steps to reproduce

I'm using your assemblyscript for subgraph mapping typescript.
this is my typescript code 
```
export function handleCollect(event: CollectEvent): void { }
``` 
when type "graph build", it doesn't occur errors in above case.
but

```
export function handleCollect(event: CollectEvent): void { if(event.transaction.to == null) {}}
```
in this case AssemblyScript occurs error like this
 Whoops, the AssemblyScript compiler has crashed during compile :-(
```
▌
▌ Here is the stack trace hinting at the problem, perhaps it's useful?
▌
▌ AssertionError: assertion failed
▌     at i.assert (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:765506)
▌     at f.compileBinaryOverload (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:280159)
▌     at f.compileBinaryExpression (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:254198)
▌     at f.compileExpression (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:245493)
▌     at f.compileIfStatement (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:236460)
▌     at f.compileStatement (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:230864)
▌     at f.compileStatements (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:231714)
▌     at f.compileFunctionBody (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:220856)
▌     at f.compileFunction (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:219868)
▌     at f.compileElement (C:\Users\TONY\AppData\Roaming\npm\node_modules\@graphprotocol\graph-cli\node_modules\assemblyscript\dist\assemblyscript.js:7:211545)
▌
▌ If it refers to the dist files, try to 'npm install source-map-support' and
▌ run again, which should then show the actual code location in the sources.
▌
▌ If you see where the error is, feel free to send us a pull request. If not,
▌ please let us know: https://github.com/AssemblyScript/assemblyscript/issues
▌
▌ Thank you!

```
Why does this error occur?

**Comment by CountBleck** [comment] 2023-09-14 23:48
If you use PowerShell, run `$env:NODE_OPTIONS = "--enable-source-maps"` and then re-run the command that caused the crash so we can see a proper stack trace.

**Comment by CountBleck** [comment] 2023-09-15 00:24
Found to be caused by an egregiously dated version of AS ([Discord forum thread](https://discord.com/channels/721472913886281818/1152025829937782894)), so closing.

**Closed by CountBleck** 2023-09-15 00:24 UTC
Labels: bug
