### ISSUE TITLE
RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by feedthejim** [AssemblyScript/assemblyscript#175] opened 2018-07-18 10:19 UTC
hi, it's me again. I'm getting the following error without any ways of debugging (for some reason, Mozilla does't execute my code.

```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at assembly/Vector3/Vector3#subtract (wasm-function[24]:5)
    at assembly/Sphere/Sphere#intersect (wasm-function[26]:12)
    at assembly/RayTracer/RayTracer#trace (wasm-function[32]:56)
    at assembly/RayTracer/RayTracer#render (wasm-function[33]:309)
    at assembly/index/init (wasm-function[34]:970)
    at WebAssembly.instantiateStreaming.then.module 
``` 
Here are the relevants bits of code.

`Vector3.ts`

```
  subtract(v2: Vector3): Vector3 {
    return new Vector3(this.x - v2.x, this.y - v2.y, this.z - v2.z);
  }
```

`Sphere.ts`

```
  intersect(rayOrigin: Vector3, rayDirection: Vector3): Intersection | null {
    let l: Vector3 = this.center.subtract(rayOrigin);
  
```

`RayTracer.ts`

```
     let transmission: Vector3 = new Vector3(1, 1, 1);
        let lightDirection = this.elements[i].center
          .subtract(intersectionPoint)
          .normalize();
        for (let j = 0; j < this.elements.length; j++) {
          if (i !== j) {
            let hitInfo: Intersection | null = this.elements[j].intersect(
              intersectionPoint.add(intersectionNormal.multiply(bias)),
              lightDirection,
            );
           
```
Any idea how I could debug my own code ? What are the best practices when using the arena allocator etc ? I haven't seen any example of using dynamic allocation on any of the projects using assemblyscript.

**Comment by MaxGraey** [comment] 2018-07-18 10:24
Can you share full code of Sphere? It might be `this.center` is null or something else.

**Comment by feedthejim** [comment] 2018-07-18 12:58
> Can you share full code of Sphere? It might be this.center is null or something else.

I uploaded the code here, I didn't bother to setup the build.

https://webassembly.studio/?f=uzglstt48n

> btw you can use operator overloading for Vector3 class

I'm pretty an issue referenced that it wasn't working. (issue #52  ?)

**Comment by MaxGraey** [comment] 2018-07-18 13:11
I finish prepare your example and don't see any exceptions:
Update version: https://webassembly.studio/?f=gp6rm11tr5o

**Comment by MaxGraey** [comment] 2018-07-18 13:13
Which is AssemblyScript version you are use and how to install?

**Comment by dcodeIO** [comment] 2018-07-21 01:36
I believe the error is here: https://github.com/feedthejim/AssemblyScriptRayTracer/blob/master/assembly/RayTracer.ts#L121

That's storing a 32-bit value somewhere where the heap lives in an unsafe way, in turn corrupting the memory. Instead, either use `--memoryBase` to reserve some fixed-size space at the start of the memory, or use `memory.allocate` to dynamically allocate a suitable chunk of memory to store to.

**Comment by feedthejim** [comment] 2018-07-21 20:13
Okay, so using the keyword `new` is definitely not the way to go along with memory.allocate because it doesn't really care if I allocated memory before, right ?

So what's the best way to use and instantiate objects without using `new` while still using memory allocation ? Creating a pointer and settings the values manually ? ..

**Comment by dcodeIO** [comment] 2018-07-21 20:35
The issue isn't with the `new` keyword in particular, but that you have been mixing dynamic memory allocation and static loads/stores in an unsafe way (here: overwriting each other). If you for example know that you'll need 8kb to store all your static stuff, use `--memoryBase 8192` to reserve it before anything else. Compiler-generated static data and the dynamic heap will be placed after that then, so you can freely use those 8KB for manual things, i.e. for a pixel buffer. You can, of course, also allocate the pixel buffer dynamically within the program, for example `var pixelBufferStart = memory.allocate(8192)` and make your loads and stored relative to that, i.e. `var pixelValue = load<u32>(pixelBufferStart + (y * WIDTH + x) * sizeof<u32>())`. Now, when accessing the pixel buffer from JS, obtain its start offset through `export function getPixelBufferStart(): usize { return pixelBufferStart; }` and use an `Uint32Array` view to work with it.

**Comment by MaxGraey** [comment] 2018-10-28 12:29
Closing. You are free to reopen it if there are more questions

**Closed by MaxGraey** 2018-10-28 12:29 UTC
Labels: question :bulb:
