### ISSUE TITLE
I hope compiling to native binary was added for AssemblyScript.

### ISSUE THREAD

**Issue by Foxchandaisuki** [AssemblyScript/assemblyscript#2824] opened 2024-03-09 06:44 UTC
### Feature suggestion

AssemblyScript is a good idea because it makes using TypeScript to make WASM available. And I hope someday compiling to native binary was supported. It would be very nice to see native binary made from AssemblyScript running on the Operating Systems like Windows, Linux, and MacOS. Using LLVM as a backend could be an option.

**Comment by coder0107git** [comment] 2024-03-09 07:13
Duplicate of #2174 .

**Closed** 2024-03-09 15:28 UTC
Labels: duplicate, enhancement
